---
- name: wait for api before using
  wait_for:
    port: "{{ dvu_api_port }}"

# curl -X PUT -d 'true' http://localhost:8080/api/admin/settings/:ProvCollectionEnabled
- name: (Optionally) Enable Provenance
  uri:
    url: "{{ dataverse.api.location }}/admin/settings/:ProvCollectionEnabled"
    method: PUT
    body: "{{ dvu_provenance_enabled | string }}"
  when: dvu_provenance_enabled

# TODO: Run the retroactive file PID registration script or register all file PID endpoint
# https://github.com/IQSS/dataverse/releases/tag/v4.9
# NOTE: this may need to be a manual, rather than an automated process
# if the provider is not fault-tolerant and supportive of the possibility of
# the job being re-run, as it appears to be a one-time operation
