---
# vars:
# - version
# - query
# - [checksum]
- name: increment database, if query exists
  block:
  - name: "download {{ version }} query"
    get_url:
      url: "{{ dvu_releases_url }}/v{{ version }}/{{ query }}"
      dest: "{{ dvu_working_dir }}"

  - name: run {{ version }} query
    command: "psql -U {{ dvu_dbuser }} -d {{ dvu_dbname }} -f {{ query }}"
    args:
      chdir: "{{ dvu_working_dir }}"

  when: query != ''
