---
- name: "run upgrade tasks for relevant versions"
  include: "upgrade_tasks.yml"
  vars:
    tasks_version:  "{{ item.version }}"
    tasks_queries:  "{{ item.queries | default([]) }}"
    tasks:    "{{ item.tasks | default(false) }}"
    tasks_metadata: "{{ item.metadata | default([]) }}"
  when: dvu_current_version is version_compare(item.version, '<') and dvu_target_version is version_compare(item.version, '>=')
  with_items: "{{ dvu_versions | union(dvu_versions_extra) }}"

- name: add custom metadata to solr
  include: solrize_metadata.yml

- name: run post-upgrade tasks
  include: post_upgrade.yml
