---
- name: "run upgrade tasks for relevant versions"
  include: "upgrade_tasks.yml"
  vars:
    tasks_version:  "{{ item.version }}"
    tasks_queries:  "{{ item.queries | default([]) }}"
    tasks:          "{{ item.tasks | default(false) }}"
    tasks_solr:     "{{ item.solr | default([]) }}"
    tasks_metadata: "{{ item.metadata | default([]) }}"
  when: dvu_current_version is version_compare(item.version, '<') and dvu_target_version is version_compare(item.version, '>=')
  with_items: "{{ dvu_versions }}"

- name: update custom metadata
  include: update_metadata.yml
  vars:
    file:     "{{ item.file }}"
    checksum: "{{ item.checksum | default(omit) }}"
    url:      "{{ item.url | default('') }}"
    local:    "{{ item.local | default(false) }}"
  with_items: "{{ dvu_extra_metadata }}"

- name: add custom metadata to solr
  include: solrize_metadata.yml

- name: run post-upgrade tasks
  include: post_upgrade.yml
