---
- name: "run upgrade tasks for relevant versions"
  include: "upgrade_tasks.yml"
  vars:
    tasks_version:  "{{ item.version }}"
    tasks_query:    "{{ item.query | default('') }}"
    tasks:    "{{ item.tasks | default(false) }}"
    checksum: "{{ item.checksum | default(omit) }}"
    metadata_file:      "{{ item.metadata_file | default('') }}"
    metadata_checksum:  "{{ item.metadata_checksum | default('') }}"
  when: dvu_current_version is version_compare(item.version, '<') and dvu_target_version is version_compare(item.version, '>=')
  with_items: "{{ dvu_versions }}"

- name: run post-upgrade tasks
  include: post_upgrade.yml
