---
- name: restart server
  command: "echo 'restarting glassfish after upgrading dataverse'"
  changed_when: true
  notify: restart glassfish

- name: flush handlers to invoke restart
  meta: flush_handlers

- name: reindex
  block:
    # curl http://localhost:8080/api/admin/index/clear
    # curl http://localhost:8080/api/admin/index
  - name: clear existing index
    uri:
      url: "{{ dvu_api_location }}/admin/index/clear"
  - name: reindex
    uri:
      url: "{{ dvu_api_location }}/admin/index"
