---

######################################################################
# Parse the metadata blocks to create Solr <fields> and <copyfields>
######################################################################

- name: parse metadata blocks (mdblocks) to get Solr copyFields
  local_action: "shell {{ role_path }}/scripts/mdblock_parser.py -c {{ instance_mdblocks_dir }}/{{ item }}.tsv"
  register: copyFields
  run_once: true
  become: false
  with_items: "{{ instance_md_blocks }}"

- name: add metadata <copyfield>s to Dataverse's Solr schema.xml
  blockinfile:
    dest: "{{ dvu_solr_config_dir }}/schema.xml"
    state: present
    insertbefore: "Dataverse Specific"
    marker: "<!-- {mark} Dataverse copyfield MANAGED BLOCK -->"
    content: "{{ copyFields.results | map(attribute='stdout') | list | join('\n') }}"
  become: true
  notify: reindex solr

- name: parse metadata blocks (mdblocks) for Solr fields
  local_action: "shell {{ role_path }}/scripts/mdblock_parser.py -f {{ instance_mdblocks_dir }}/{{ item }}.tsv"
  register: fields
  run_once: true
  become: false
  with_items: "{{ instance_md_blocks }}"

- name: add metadata <field>s to Dataverse's Solr schema.xml
  blockinfile:
    dest: "{{ dvu_solr_config_dir }}/schema.xml"
    state: present
    insertafter: "^\\s*<field name=[^>]*>"
    marker: "<!-- {mark} Dataverse field MANAGED BLOCK -->"
    content: "{{ fields.results | map(attribute='stdout') | list | join('\n') }}"
  become: true
  notify: reindex solr

- name: restart solr
  service:
    name: solr
    state: restarted
  become: true
