---
- name: find needed version upgrades
  debug:
    msg: "version {{ item.version }} is needed"
  when: dvu_current_version is version_compare(item.version, '<') and dvu_target_version is version_compare(item.version, '>=')
  with_items: "{{ dvu_versions }}"
