---
# vars:
# - version
# - query
# - [checksum]
- name: "run database upgrade tasks for relevant versions"
  include: "increment_database.yml"
  vars:
    version: "{{ tasks_version }}"
    query:    "{{ tasks_query | default('') }}"
    checksum: "{{ checksum | default(omit) }}"

- name: "run additional upgrade tasks for {{ tasks_version }}"
  include: "{{ tasks_version }}.yml"
  vars:
    version: "{{ tasks_version }}"
  when: tasks
