---
# vars:
# - version
# - query

- name: "deploy dataverse {{ tasks_version }}"
  include: "update_war.yml"
  vars:
    version: "{{ tasks_version }}"

# LeSoN
- name: "run database upgrade tasks for relevant versions"
  include: "increment_database.yml"
  vars:
    version: "{{ tasks_version }}"
    query:    "{{ tasks_query }}"
  with_items:
  - "{{ tasks_queries }}"
  loop_control:
    loop_var: tasks_query
    
- name: "run additional upgrade tasks for {{ tasks_version }}"
  include: "{{ tasks_version }}.yml"
  vars:
    version: "{{ tasks_version }}"
  when: tasks
