---
# vars:
# - version
# - query
# - [checksum]
- name: "run database upgrade tasks for relevant versions"
  include: "increment_database.yml"
  vars:
    version: "{{ tasks_version }}"
    query:    "{{ tasks_query }}"
  with_items:
  - "{{ tasks_queries }}"
  loop_control:
    loop_var: tasks_query

- name: "update metadata for {{ tasks_version }}"
  include: "update_metadata.yml"
  vars:
    version: "{{ tasks_version }}"
    file: "{{ metadata_file | default('') }}"
    checksum: "{{ metadata_checksum | default('') }}"
  when: metadata_file != ''

- name: "run additional upgrade tasks for {{ tasks_version }}"
  include: "{{ tasks_version }}.yml"
  vars:
    version: "{{ tasks_version }}"
  when: tasks
